@ECHO OFF
COLOR 0a
cls
ECHO. +--------------------------+
ECHO. +                          +
ECHO. +     System Profiling     +
ECHO. +                          +
ECHO. +--------------------------+
ECHO.
ECHO.
echo [+] DATA e ORA DI INIZIO: %DATE% - %TIME%
ECHO. && ECHO. && ECHO. && ECHO. 
ECHO [+] ATTENDERE IL COMPLETAMENTO DELL'OPERAZIONE...
ECHO.
mkdir REPORTING
echo .:.:./     Profilazione del sistema     \.:.:.   >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
echo [+] DATA e ORA DI INIZIO: %DATE% - %TIME%  >>REPORTING\REPORT.TXT 
ECHO.>>REPORTING\REPORT.TXT &&  ECHO.>>REPORTING\REPORT.TXT
echo **************************************** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT &&  ECHO.>>REPORTING\REPORT.TXT &&  ECHO.>>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** INFORMAZIONI GENERALI DEL SISTEMA ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
systeminfo >>REPORTING\REPORT.TXT 
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** INFORMAZIONI GENERALI DELLA WORKSTATION ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
net config workstation >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** UTENTE ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
WHOAMI >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** NOME HOST ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
HOSTNAME >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** VERSIONE OS ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
VER >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** DATA, ORA e FUSO ORARIO ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
DATE /T >>REPORTING\REPORT.TXT && TIME /T >>REPORTING\REPORT.TXT   && TZUTIL /g  >>REPORTING\REPORT.TXT 
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** INTERFACCE DI RETE ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
IPCONFIG /ALL >>REPORTING\REPORT.TXT && IPCONFIG /DISPLAYDNS >>REPORTING\REPORT.TXT 
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** VARIABILI D'AMBIENTE ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
SET >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** CACHE ARP ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
ARP -A >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** CONNESSIONI ATTIVE ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
NETSTAT -ANO >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** CONDIVISIONI ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
NET SHARE >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** TASKLIST PROCESSI E SERVIZI ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT
TASKLIST >>REPORTING\REPORT.TXT && TASKLIST /M >>REPORTING\REPORT.TXT && TASKLIST /SVC >>REPORTING\REPORT.TXT
ECHO.>>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT && echo *********** UTENTI LOCALI O REMOTI CHE HANNO EFFETTUATO IL LOGIN ********** >>REPORTING\REPORT.TXT && ECHO.>>REPORTING\REPORT.TXT 
NET USER >>REPORTING\REPORT.TXT && NET USER %username% >>REPORTING\REPORT.TXT
cd REPORTING
cd >cd.txt 
set /P p=<cd.txt
del cd.txt
cd \
dir /s/b/o:n/A:D >>%p%\directory_name.txt
echo [+] DATA e ORA DI FINE: %DATE% - %TIME% >>REPORTING\REPORT.TXT 
pause







